name: Ubuntu build

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install X11 on macOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz

      - name: Install X11 on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xorg

      - name: build
        run: ./configure && make
