name: Build

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install X11 on macOS
        if: runner.os == 'macOS'
        run: brew install xquartz

      - name: Install X11 on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xorg

      # consolidate macOS and Ubuntu builds after fixing ./configure on macOS
      - name: Build on macOS
        if: runner.os == 'macOS'
        run: |
          ./configure --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib
          make

      - name: Build on Ubuntu
        if: runner.os == 'Linux'
        run: ./configure && make
